### ISSUE TITLE
Order seems wrong

### ISSUE THREAD

**Issue by timczerniak** [eoghanmurray/lookup-irish#2]
Hello,

Thank you so much for putting the Anki deck together, I was looking for something to expand my vocabulary and had considered writing something to automatically pull from the word frequency lists and put into a flash-card app. Turns out you did it already.

I'm having an issue, however. When I import the deck to Anki, the order that the words are introduced seems wrong. As I understand, Anki introduces new words in the order of the 'Due' field. This should be the order that you add cards to a deck, but that doesn't seem to be the case. I have attached a shot of the cards ordered by the 'Due' field straight after import, and it appears to start at row ~2000 in your google sheet. The first word is 'thar ceann', New#6784. 'an' (row 1 in your sheet) is New#19606.

![Screenshot 2020-07-03 at 15 30 59](https://user-images.githubusercontent.com/1238400/86478491-39986000-bd42-11ea-9160-6f8ce00bdab4.png)

Any idea why this may be happening? I'm also happy to contribute by the way (I'm a SWE by day).
Thanks,
Tim.

**Comment by eoghanmurray** [comment]
Hi Tim,

Wonderful to hear of someone making use of the deck!

This Deck was built on one published originally at https://ankiweb.net/shared/info/1975966926 (started by https://github.com/terrysimons)

The version from this repository lives at https://ankiweb.net/shared/info/1128787897

So maybe there was never a full export done from scratch; we've (myself and Terry) been using an ad-hoc export process from Google Docs to overwrite/update our local deck.
I think it's something as follows (mainly from memory) 
 - Google Docs > export to CSV
 - Check that your empty Anki deck has the following fields in the following order (I'm usually updating an existing deck so not quite sure how a new deck is created):
    -- GA
    -- PoS (Part of speech)
    -- EN
    -- Gender
    -- GenitiveVN   (this is additional info on the front of the card below where the GA column is displayed)
    -- NTeanglann
    -- NFocloir
    -- Tags (note this field is built in to Anki so may not need to be explicitly defined)

 - delete the first heading row from the .csv (after checking columns are in the correct order).  The order of columns corresponds to the above (legacy) column order
 - browse to your empty deck in Anki
 - import using File > Import.. and select the .csv
 - Check the field mapping corresponds to above ordering
 - Chose 'Update' rather than 'Ignore' (irrelevant on first import)
 - Select 'Allow HTML in fields'

So Terry sent me an email with instructions on all this last year, I can forward it on to you if you like.
And also grant access to the Google Docs if you wish to update directly there.

Let me know if github doesn't show access to my email address?

**Comment by eoghanmurray** [comment]
And sorry, I didn't address why the 'due' field is getting populated as you described; I'm at a loss!

You've highlighted some todos then:
 - include an empty Anki template in this repository (does such a thing exist)
 - include a .csv export from the Google spreadsheet directly in this repository, with any tools needed to manipulate it.  I'm open to alternatives to Google docs for the 'master' information, and toyed previously with publishing a website where the flashcards would be viewable outside of Anki, and also editable there.
 - myself and Terry also talked about publishing a dedicated mobile app as you have to be somewhat bought in to Anki to be able to discover/use decks, and an app would enable lots of other cool features!

**Comment by timczerniak** [comment]
Thanks for that Eoghan,

I tried that method of direct to CSV and import to Anki, and it worked a treat, everything in the right order now.

I found that if I had zero cards in the database, then hit Menu -> Check Database before the CSV import, it optimised the database so I ended up with 'an' being New#0 when it was imported. Then, before doing any Study, I exported the deck as a .apkg file (including the scheduling information) and imported it into another profile, and that worked well. I have the .apkg file if you want it.

I don't think Anki note-type templates really exist. I have read that if you have a deck with a single card in it, that's enough to install the note-type in someone's anki database, so you could have a single-card deck in a .apkg file which can be used as the template.

In any case, I'm happy to have edit access to the sheet, but it looks pretty damn good to me already. I actually think a google sheet is a good source-of-truth for this, because it's easily editable/fixable, and you can import it from there to any other format.

In any case, I'm going to import the deck as it is and start studying and if I find anything else I'll let you know. Your email address on github just says 'any address at the domain <xxxxxxx.yyy>', so if that's accurate, I'll just pick an address to mail if I find anything else :)

Cheers,
Tim.

**Comment by eoghanmurray** [comment]
Great Tim,
I was very active with this project about 8 months ago, and I took it over from Terry who started it off but who also spreads his focus on other projects (including other Irish projects).  It'll be great to get an injection of a new perspective into this!
Send me an email and I'll set you up with full Google Sheets editing.

Eoghan
